spring:
  datasource:
#    url: datasource_url
#    username: datasource_username
#    password: datasource_password
    url: jdbc:mysql://airbnb-db.cabi5bwgwykn.ap-northeast-2.rds.amazonaws.com:3306/airbnb
    username: team11
    password: Password1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: true
logging:
  level:
    com.team11: debug

